services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 book_exchange.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=False

  db:
    image: sqlite:3
    volumes:
      - db_data:/app/data

volumes:
  static_volume:
  db_data: